title: ArisHu
description: # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

encoding: utf-8
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hytc1106hwc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here


# Author Settings
author: Aris Hu # add your name
author-img: Aris-Hu.png # add your photo
about-author: 感谢所有帮助我的人 # add description
#twitter: "" # add your Twitter handle
#facebook: "" # add your Facebook handle
github: hytc1106hwc # add your Github handle
linkedin: huwencheng # add your Linkedin handle
email: 1729116521@qq.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
